[package]
name = "rust-latte-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
ariadne = "0.1"
chumsky = "0.8"

[dev-dependencies]
insta = "1"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

