[package]
name = "rust-latte-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.6"
lalrpop-util = { version = "0.23", features = ["lexer"] }
logos = "0.16"
tempfile = "3"
inkwell = {
    version = "0.10",
    default-features = false,
    features = [
        "llvm14-0-force-static",
        "target-x86",
    ]
}

[dev-dependencies]
insta = "1"
libtest-mimic = "0.8"

[[test]]
name = "fixtures"
path = "tests/fixtures.rs"
harness = false

[build-dependencies]
lalrpop = "0.23"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
