use crate::lexer::Spanned;
use crate::ast::*;
use crate::lexer::Token;
use crate::lexer::LexingError;

grammar<'input>;

pub Program: Program = Spanned<FnDecl>* => Program(<>);

extern {
    type Location = usize;
    type Error = Spanned<LexingError>;

    enum Token {
        "true" => Token::True,
        "false" => Token::False,
        "num" => Token::Num(<i64>),
        "str" => Token::Str(<String>),
        "ident" => Token::Ident(<String>),
        "if" => Token::If,
        "else" => Token::Else,
        "while" => Token::While,
        "return" => Token::Return,
        "{" => Token::LBrace,
        "}" => Token::RBrace,
        "(" => Token::LParen,
        ")" => Token::RParen,
        "," => Token::Comma,
        ";" => Token::Semicolon,
        "+" => Token::Plus,
        "-" => Token::Minus,
        "*" => Token::Star,
        "/" => Token::Slash,
        "%" => Token::Percent,
        "!" => Token::Bang,
        "=" => Token::Equal,
        "==" => Token::EqualEqual,
        "!=" => Token::BangEqual,
        "<" => Token::Less,
        "<=" => Token::LessEqual,
        ">" => Token::Greater,
        ">=" => Token::GreaterEqual,
        "&&" => Token::AmpersandAmpersand,
        "||" => Token::PipePipe,
        "++" => Token::PlusPlus,
        "--" => Token::MinusMinus,
    }

}

Comma<Rule>: Vec<Rule> = {
    <mut v:(<Rule> ",")*> <e:Rule?> => match e {
        None => v,
        Some(e) => {
            v.push(e);
            v
        }
    }
};

CommaNonEmpty<Rule>: Vec<Rule> = {
    <mut v:(<Rule> ",")*> <e:Rule> => {
        v.push(e);
        v
    }
};

Spanned<Rule>: Spanned<Rule> =
    <l: @L> <rule: Rule> <r: @R> =>
        Spanned::new(l..r, rule);


Type: TypeName = <s:"ident"> => TypeName(s.to_string());

Ident: Ident = <s:"ident"> => Ident(s.to_string());

Block: Block = "{" <stmts: Spanned<Stmt>*> "}" => Block(stmts);

Item: Item = {
    <ident:Spanned<Ident>> "=" <e:Spanned<Expr>> => Item {
          ident,
          init: Some(e),
     },
    <ident:Spanned<Ident>> => Item {
          ident,
          init: None,
     },
};

Arg: Arg = <ty:Spanned<Type>> <name:Spanned<Ident>> => Arg { ty, name };

VarDecl: VarDecl =
    <ty: Spanned<Type>> <items: CommaNonEmpty<Spanned<Item>>> ";" => VarDecl {
        ty,
        items,
    };

FnDecl: FnDecl =
    <return_type: Spanned<Type>> <name: Spanned<Ident>> "(" <args: Comma<Spanned<Arg>>> ")" <body: Spanned<Block>> => FnDecl {
          return_type,
          name,
          args,
          body,
     };

Stmt = Stmt_<"I">; // Handle dangling elses

Stmt_<I>: Stmt = {
    ";" => Stmt::Empty,
    <b:Spanned<Block>> => Stmt::Block(b),
    <d:Spanned<VarDecl>> => Stmt::Decl(d),
    <target:Spanned<Ident>> "=" <expr:Spanned<Expr>> ";" => Stmt::Assignment { target, expr },
    "return" <expr:Spanned<Expr>> ";" => Stmt::Return(Some(expr)),
    "return" ";" => Stmt::Return(None),
    "if" "(" <cond:Spanned<Expr>> ")" <then:Spanned<Stmt_<"I">>> if I != "" => Stmt::If { cond, then: Box::new(then), otherwise: None },
    "if" "(" <cond:Spanned<Expr>> ")" <then:Spanned<Stmt_<"">>> "else" <otherwise:Spanned<Stmt_<I>>> =>
         Stmt::If { cond, then: Box::new(then), otherwise: Some(Box::new(otherwise)) },
    "while" "(" <cond:Spanned<Expr>> ")" <body:Spanned<Stmt_<I>>> => Stmt::While { cond, body: Box::new(body) },
    <e:Spanned<Expr>> ";" => Stmt::Expr(e),
    <target:Spanned<Expr>> "++" => Stmt::Incr(target),
    <target:Spanned<Expr>> "--" => Stmt::Decr(target),

};

BinaryTier<Op, NextTier>: Expr = {
    <lhs:Spanned<BinaryTier<Op, NextTier>>> <op:Spanned<Op>> <rhs:Spanned<NextTier>> => Expr::Binary {
          op,
          lhs: Box::new(lhs),
          rhs: Box::new(rhs),
     },
    <e:NextTier> => e
};

UnaryTier<NextTier>: Expr = {
    <op:Spanned<UnaryOp>> <e:Spanned<UnaryTier<NextTier>>> => Expr::Unary { op, expr: Box::new(e) },
    <e:NextTier> => e,
};

Expr = LogicalOr;
LogicalOr = BinaryTier<LogicalOrOp, LogicalAnd>;
LogicalAnd = BinaryTier<LogicalAndOp, Comparison>;
Comparison = BinaryTier<ComparisonOp, Sum>;
Sum = BinaryTier<SumOp, Product>;
Product = BinaryTier<ProductOp, Unary>;
Unary = UnaryTier<Term>;

UnaryOp: UnaryOp = {
    "-" => UnaryOp::Neg,
    "!" => UnaryOp::Not,
};

ProductOp: BinaryOp = {
    "*" => BinaryOp::Mul,
    "/" => BinaryOp::Div,
    "%" => BinaryOp::Mod,
};

SumOp: BinaryOp = {
    "+" => BinaryOp::Add,
    "-" => BinaryOp::Sub,
};

ComparisonOp: BinaryOp = {
    "<" => BinaryOp::Lt,
    "<=" => BinaryOp::Lte,
    ">" => BinaryOp::Gt,
    ">=" => BinaryOp::Gte,
    "==" => BinaryOp::Eq,
    "!=" => BinaryOp::Neq,
};

LogicalAndOp: BinaryOp = {
    "&&" => BinaryOp::And,
};

LogicalOrOp: BinaryOp = {
    "||" => BinaryOp::Or,
};

Literal: Literal = {
    <l:@L> <i:"num"> <r:@R> =>? i32::try_from(i)
        .map(Literal::Int)
        .map_err(|_| lalrpop_util::ParseError::User {
            error: Spanned::new(l..r, LexingError::IntegerOutOfRange),
        }),
    "true" => Literal::Bool(true),
    "false" => Literal::Bool(false),
    <s:"str"> => Literal::String(s),
};

Term: Expr = {
    <i:Ident> => Expr::Variable(i),
    <l:Literal> => Expr::Literal(l),
    <target:Spanned<Term>> "(" <args:Comma<Spanned<Expr>>> ")" => Expr::Application { target: Box::new(target), args },
    "(" <e:Expr> ")" => e,
};
